name: run Postman API tests
on: 
  push:
    branches:
      - 'main'
      - 'feature/**'
    paths-ignore:
      - 'Postman Collections/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: puskarojha/hello-world

      - name: start the app
        run: |
          docker run -d -p 3005:80 -v ${{ github.workspace }}/db.json:/data/db.json clue/json-server

      - name: run postman tests
        uses: matt-ball/newman-action@master
        with:
          collection: "Postman Collections/albums.json"
