name: run Postman API tests
on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run postman tests
        uses: matt-ball/newman-action@master
        with:
          collection: collection.json
